# Generated by Django 4.2.7 on 2023-12-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeFriendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
