# Generated by Django 4.2.5 on 2023-10-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeFriendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
