# Generated by Django 4.2.6 on 2023-11-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeFriendApp', '0003_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
